### ISSUE TITLE
录制的视频速度异常

### ISSUE THREAD

**Issue by TheLittleBoy** [zhfeng20108/ZFScreenRecorder#3]
视频的前半程特别快，后半程没东西。 iPad，iOS 11.1

**Comment by YJSai** [comment]
遇到相同問題,發現在iOS 10.1版之後ZFScreenVideoCamera裡的timerAction函式不會被每秒呼叫30次，最多每秒呼叫12次，frame不夠造成影片異常。暫時的解法是：
videoFrameTime.value += 33333333;
上面那行右邊數值改成 83333333，但這樣只有12FPS ，不知道有什麼方法可以讓timerAction跟之前一樣被呼叫30次

**Comment by TheLittleBoy** [comment]
我猜测是苹果降频造成的

**Comment by YJSai** [comment]
有可能,目前三台機器iPad air 2跟iPad air 還有iPad Pro的iOS 分別是10.1 ,10.3,11.2，只有iPad air 2能維持30 FPS

**Comment by zhfeng20108** [comment]
@TheLittleBoy @YJSai preferredFramesPerSecond （iOS10用这个方法） 标识每秒钟调用几次，比如每秒钟调用10次，那就是每0.1秒调用一次; frameInterval （ios10被弃用）, 这样就能維持30 FPS
